/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A namespaced, imperative intent. Adjacently tagged as
 * `{ "type": <namespace>, "data": <leaf> }`, mirroring [`super::Event`]; leaf
 * variants land additively inside each namespace enum (FR-007).
 */
export type Command =
  | {
      type: "run";
      data: RunCommand;
    }
  | {
      type: "goal";
      data: GoalCommand;
    }
  | {
      type: "vault";
      data: VaultCommand;
    }
  | {
      type: "voice";
      data: VoiceCommand;
    }
  | {
      type: "ui";
      data: UiCommand;
    }
  | {
      type: "ext";
      data: {
        ns: string;
        name: string;
        version: number;
        payload: unknown;
      };
    };
/**
 * Run-namespace intents.
 */
export type RunCommand = {
  type: "start";
  data: {
    goal: string;
  };
};
/**
 * Goal-namespace intents.
 */
export type GoalCommand = {
  type: "add";
  data: {
    title: string;
  };
};
/**
 * Vault-namespace intents.
 */
export type VaultCommand = {
  type: "update_note";
  data: {
    path: string;
    body: string;
  };
};
/**
 * Voice-namespace intents.
 */
export type VoiceCommand = {
  type: "speak";
  data: {
    text: string;
  };
};
/**
 * UI-namespace intents.
 */
export type UiCommand = {
  type: "focus_surface";
  data: {
    surface: string;
  };
};
