/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A unique, sortable event id (ULID), serialized as a Crockford-base32 string.
 */
export type EventId = string;
/**
 * An RFC 3339 timestamp. Carried as a string at the contract boundary; parsed
 * to a calendar type only where a consumer needs ordering (`011`).
 */
export type Timestamp = string;
/**
 * The kind of participant behind a [`ParticipantId`].
 */
export type ParticipantKind = "goal_loop" | "agent" | "connector" | "scheduler" | "ui" | "system";
/**
 * The ordering scope of an event (FR-005). `Run` is the common case; new kinds
 * are added additively.
 */
export type StreamId =
  | {
      type: "run";
      data: string;
    }
  | {
      type: "agent";
      data: string;
    }
  | {
      type: "workspace";
      data: string;
    };
/**
 * A namespaced, past-tense fact carried by the bus. Adjacently tagged as
 * `{ "type": <namespace>, "data": <leaf> }`. The namespace set is the **stable
 * structure**; leaf variants land additively inside each namespace enum without
 * editing this core (FR-006).
 */
export type Event =
  | {
      type: "run";
      data: RunEvent;
    }
  | {
      type: "goal";
      data: GoalEvent;
    }
  | {
      type: "vault";
      data: VaultEvent;
    }
  | {
      type: "voice";
      data: VoiceEvent;
    }
  | {
      type: "ui";
      data: UiEvent;
    }
  | {
      type: "ext";
      data: {
        ns: string;
        name: string;
        version: number;
        payload: unknown;
      };
    };
/**
 * Run-namespace facts. The migrated `wagner://*` run-execution channels land
 * here (P2): the bus carries the real payloads so the `UiGateway` can re-emit
 * the legacy Tauri events byte-identically.
 */
export type RunEvent =
  | {
      type: "finished";
      data: {
        run_id: string;
        ok: boolean;
      };
    }
  | {
      type: "snapshot";
      data: unknown;
    }
  | {
      type: "activity";
      data: unknown;
    }
  | {
      type: "transmission";
      data: unknown;
    }
  | {
      type: "workflow_step";
      data: unknown;
    }
  | {
      type: "workflow_done";
      data: unknown;
    };
/**
 * Goal-namespace facts.
 */
export type GoalEvent = {
  type: "added";
  data: {
    goal_id: string;
    title: string;
  };
};
/**
 * Vault-namespace facts.
 */
export type VaultEvent = {
  type: "note_updated";
  data: {
    path: string;
    rev: number;
  };
};
/**
 * Voice-namespace facts.
 */
export type VoiceEvent =
  | {
      type: "utterance_transcribed";
      data: {
        text: string;
      };
    }
  | {
      type: "download_progress";
      data: unknown;
    };
/**
 * UI-namespace facts.
 */
export type UiEvent =
  | {
      type: "surface_focused";
      data: {
        surface: string;
      };
    }
  | {
      type: "panel";
      data: {
        operative_id: string;
        spec: unknown;
      };
    };

/**
 * The unit carried by the bus: a typed `Event` payload wrapped with identity,
 * ordering, and scope (FR-001/FR-002). `stream` + monotonic `seq` make
 * per-stream ordering expressible (enforcement is `011` P1).
 */
export interface Envelope {
  /**
   * Schema-version id (FR-016) — always `"envelope.v1"` for this version.
   */
  schema: string;
  id: EventId;
  ts: Timestamp;
  origin: ParticipantId;
  stream: StreamId;
  seq: number;
  scope: Scope;
  payload: Event;
}
/**
 * Stable identity of a participant (FR-003): which peer/machine, what kind, a
 * stable logical name, and a per-instance id.
 */
export interface ParticipantId {
  /**
   * The peer/machine identity (iroh node id, z-base-32).
   */
  node: string;
  kind: ParticipantKind;
  /**
   * A stable logical name (e.g. `"goal-loop"`, `"slack-connector"`).
   */
  name: string;
  /**
   * Distinguishes two live instances of the same logical name.
   */
  instance: string;
}
/**
 * The multi-tenant filter seam (FR-004) — exactly `{user, workspace}` in v1; an
 * org tier or further fields are added additively when multi-tenant lands.
 */
export interface Scope {
  user: string;
  workspace: string;
}
