/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A namespaced, past-tense fact carried by the bus. Adjacently tagged as
 * `{ "type": <namespace>, "data": <leaf> }`. The namespace set is the **stable
 * structure**; leaf variants land additively inside each namespace enum without
 * editing this core (FR-006).
 */
export type Event =
  | {
      type: "run";
      data: RunEvent;
    }
  | {
      type: "goal";
      data: GoalEvent;
    }
  | {
      type: "vault";
      data: VaultEvent;
    }
  | {
      type: "voice";
      data: VoiceEvent;
    }
  | {
      type: "ui";
      data: UiEvent;
    }
  | {
      type: "ext";
      data: {
        ns: string;
        name: string;
        version: number;
        payload: unknown;
      };
    };
/**
 * Run-namespace facts.
 */
export type RunEvent = {
  type: "finished";
  data: {
    run_id: string;
    ok: boolean;
  };
};
/**
 * Goal-namespace facts.
 */
export type GoalEvent = {
  type: "added";
  data: {
    goal_id: string;
    title: string;
  };
};
/**
 * Vault-namespace facts.
 */
export type VaultEvent = {
  type: "note_updated";
  data: {
    path: string;
    rev: number;
  };
};
/**
 * Voice-namespace facts.
 */
export type VoiceEvent = {
  type: "utterance_transcribed";
  data: {
    text: string;
  };
};
/**
 * UI-namespace facts.
 */
export type UiEvent = {
  type: "surface_focused";
  data: {
    surface: string;
  };
};
