/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A namespaced, past-tense fact carried by the bus. Adjacently tagged as
 * `{ "type": <namespace>, "data": <leaf> }`. The namespace set is the **stable
 * structure**; leaf variants land additively inside each namespace enum without
 * editing this core (FR-006).
 */
export type Event =
  | {
      type: "run";
      data: RunEvent;
    }
  | {
      type: "goal";
      data: GoalEvent;
    }
  | {
      type: "vault";
      data: VaultEvent;
    }
  | {
      type: "voice";
      data: VoiceEvent;
    }
  | {
      type: "ui";
      data: UiEvent;
    }
  | {
      type: "ext";
      data: {
        ns: string;
        name: string;
        version: number;
        payload: unknown;
      };
    };
/**
 * Run-namespace facts. The migrated `wagner://*` run-execution channels land
 * here (P2): the bus carries the real payloads so the `UiGateway` can re-emit
 * the legacy Tauri events byte-identically.
 */
export type RunEvent =
  | {
      type: "finished";
      data: {
        run_id: string;
        ok: boolean;
      };
    }
  | {
      type: "snapshot";
      data: unknown;
    }
  | {
      type: "activity";
      data: unknown;
    }
  | {
      type: "transmission";
      data: unknown;
    }
  | {
      type: "workflow_step";
      data: unknown;
    }
  | {
      type: "workflow_done";
      data: unknown;
    };
/**
 * Goal-namespace facts.
 */
export type GoalEvent = {
  type: "added";
  data: {
    goal_id: string;
    title: string;
  };
};
/**
 * Vault-namespace facts.
 */
export type VaultEvent = {
  type: "note_updated";
  data: {
    path: string;
    rev: number;
  };
};
/**
 * Voice-namespace facts.
 */
export type VoiceEvent =
  | {
      type: "utterance_transcribed";
      data: {
        text: string;
      };
    }
  | {
      type: "download_progress";
      data: unknown;
    };
/**
 * UI-namespace facts.
 */
export type UiEvent =
  | {
      type: "surface_focused";
      data: {
        surface: string;
      };
    }
  | {
      type: "panel";
      data: {
        operative_id: string;
        spec: unknown;
      };
    };
