/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The v1 event/command namespaces a plugin may emit or subscribe to.
 */
export type Namespace = "run" | "goal" | "vault" | "voice" | "ui" | "ext";
/**
 * The **closed** v1 capability vocabulary (FR-014): the coarse permission kinds
 * a plugin may request. Honored on trust today (declared, not enforced — the
 * sandbox is deferred, `specs/012` §13.7); the set grows additively. No
 * per-path/per-host scoping in v1.
 */
export type Capability =
  | "network"
  | "process.spawn"
  | "vault.read"
  | "vault.write"
  | "fs.read"
  | "fs.write"
  | "secrets.read";

/**
 * The uniform plugin manifest (FR-012): what a plugin provides, the namespaces
 * it emits/subscribes, the schemas it registers, the capabilities it requests,
 * and its stability tier. An empty `capabilities` set is valid — a pure
 * subscriber requests nothing (EC-004).
 */
export interface PluginManifest {
  /**
   * Logical names of the participants (each an `Agent`) this plugin provides.
   */
  participants_provided: string[];
  emits: Namespace[];
  subscribes: Namespace[];
  registered_schemas: SchemaRef[];
  capabilities: Capability[];
  /**
   * The stability tier of a contract type (FR-010). A newly added type defaults
   * to `Experimental`; promotion to `Stable` (which binds the no-break rule
   * FR-017) is a deliberate change; `Internal` is for engine-private types.
   */
  stability?: "stable" | "experimental" | "internal";
}
/**
 * A reference to a JSON Schema a plugin registers (name + version).
 */
export interface SchemaRef {
  name: string;
  version: number;
}
