// Generates shared/contracts/index.ts — a barrel re-exporting the primary type
// of each exported bus schema. Run by `npm run gen:contracts` after json2ts.
//
// Each schema file (envelope/event/command/plugin_manifest) is generated
// independently, so each .d.ts inlines its own copy of shared nested types
// (e.g. `Event` appears in both envelope.d.ts and event.d.ts). Re-exporting only
// the primary type (the schema `title`) from each module keeps the barrel
// collision-free; deep nested types stay reachable via their own module.
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url)); // shared/scripts
const schemasDir = join(here, "..", "..", "edge", "host", "schemas", "bus");
const outFile = join(here, "..", "contracts", "index.ts");

const lines = ["// Generated by `npm run gen:contracts` — do not edit by hand.", ""];
let count = 0;
for (const file of readdirSync(schemasDir).filter((f) => f.endsWith(".json")).sort()) {
  const stem = file.replace(/\.json$/, "");
  const { title } = JSON.parse(readFileSync(join(schemasDir, file), "utf8"));
  if (!title) continue;
  lines.push(`export type { ${title} } from "./${stem}";`);
  count += 1;
}
writeFileSync(outFile, lines.join("\n") + "\n");
console.log(`contracts barrel: ${count} type(s) → ${outFile}`);
